'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ext2.smsexpert.mx/soap/smsexpert", ConfigurationName:="ServiceReference1.smsexpertPortType")>  _
    Public Interface smsexpertPortType
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje envio_smsRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/envio_sms", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function envio_sms(ByVal request As ServiceReference1.envio_smsRequest) As ServiceReference1.envio_smsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/envio_sms", ReplyAction:="*")>  _
        Function envio_smsAsync(ByVal request As ServiceReference1.envio_smsRequest) As System.Threading.Tasks.Task(Of ServiceReference1.envio_smsResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje consulta_smsRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consulta_sms", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function consulta_sms(ByVal request As ServiceReference1.consulta_smsRequest) As ServiceReference1.consulta_smsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consulta_sms", ReplyAction:="*")>  _
        Function consulta_smsAsync(ByVal request As ServiceReference1.consulta_smsRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_smsResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje envio_sms_masivoRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/envio_sms_masivo"& _ 
            "", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function envio_sms_masivo(ByVal request As ServiceReference1.envio_sms_masivoRequest) As ServiceReference1.envio_sms_masivoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/envio_sms_masivo"& _ 
            "", ReplyAction:="*")>  _
        Function envio_sms_masivoAsync(ByVal request As ServiceReference1.envio_sms_masivoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.envio_sms_masivoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje consulta_sms_masivoRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consulta_sms_mas"& _ 
            "ivo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function consulta_sms_masivo(ByVal request As ServiceReference1.consulta_sms_masivoRequest) As ServiceReference1.consulta_sms_masivoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consulta_sms_mas"& _ 
            "ivo", ReplyAction:="*")>  _
        Function consulta_sms_masivoAsync(ByVal request As ServiceReference1.consulta_sms_masivoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_sms_masivoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje consultar_saldoRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consultar_saldo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function consultar_saldo(ByVal request As ServiceReference1.consultar_saldoRequest) As ServiceReference1.consultar_saldoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consultar_saldo", ReplyAction:="*")>  _
        Function consultar_saldoAsync(ByVal request As ServiceReference1.consultar_saldoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consultar_saldoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje envio_sms_internacionalRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/envio_sms_intern"& _ 
            "acional", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function envio_sms_internacional(ByVal request As ServiceReference1.envio_sms_internacionalRequest) As ServiceReference1.envio_sms_internacionalResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/envio_sms_intern"& _ 
            "acional", ReplyAction:="*")>  _
        Function envio_sms_internacionalAsync(ByVal request As ServiceReference1.envio_sms_internacionalRequest) As System.Threading.Tasks.Task(Of ServiceReference1.envio_sms_internacionalResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje consulta_sms_internacionalRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consulta_sms_int"& _ 
            "ernacional", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function consulta_sms_internacional(ByVal request As ServiceReference1.consulta_sms_internacionalRequest) As ServiceReference1.consulta_sms_internacionalResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consulta_sms_int"& _ 
            "ernacional", ReplyAction:="*")>  _
        Function consulta_sms_internacionalAsync(ByVal request As ServiceReference1.consulta_sms_internacionalRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_sms_internacionalResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje agregar_lista_negraRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/agregar_lista_ne"& _ 
            "gra", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function agregar_lista_negra(ByVal request As ServiceReference1.agregar_lista_negraRequest) As ServiceReference1.agregar_lista_negraResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/agregar_lista_ne"& _ 
            "gra", ReplyAction:="*")>  _
        Function agregar_lista_negraAsync(ByVal request As ServiceReference1.agregar_lista_negraRequest) As System.Threading.Tasks.Task(Of ServiceReference1.agregar_lista_negraResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje eliminar_lista_negraRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/eliminar_lista_n"& _ 
            "egra", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function eliminar_lista_negra(ByVal request As ServiceReference1.eliminar_lista_negraRequest) As ServiceReference1.eliminar_lista_negraResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/eliminar_lista_n"& _ 
            "egra", ReplyAction:="*")>  _
        Function eliminar_lista_negraAsync(ByVal request As ServiceReference1.eliminar_lista_negraRequest) As System.Threading.Tasks.Task(Of ServiceReference1.eliminar_lista_negraResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje consultar_lista_negraRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consultar_lista_"& _ 
            "negra", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function consultar_lista_negra(ByVal request As ServiceReference1.consultar_lista_negraRequest) As ServiceReference1.consultar_lista_negraResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/consultar_lista_"& _ 
            "negra", ReplyAction:="*")>  _
        Function consultar_lista_negraAsync(ByVal request As ServiceReference1.consultar_lista_negraRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consultar_lista_negraResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor () del mensaje pausar_envio_campanaRequest no coincide con el valor predeterminado (http://ext2.smsexpert.mx/soap/smsexpert)
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/pausar_envio_cam"& _ 
            "pana", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function pausar_envio_campana(ByVal request As ServiceReference1.pausar_envio_campanaRequest) As ServiceReference1.pausar_envio_campanaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ext2.smsexpert.mx/index.php?ACTION=WEBSERVICE:LOAD_NUSOAP/pausar_envio_cam"& _ 
            "pana", ReplyAction:="*")>  _
        Function pausar_envio_campanaAsync(ByVal request As ServiceReference1.pausar_envio_campanaRequest) As System.Threading.Tasks.Task(Of ServiceReference1.pausar_envio_campanaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="envio_sms", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class envio_smsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public destino As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public sms As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal sms As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.destino = destino
            Me.sms = sms
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="envio_smsResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class envio_smsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consulta_sms", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consulta_smsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public destino As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public fecha_solicitud As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal fecha_solicitud As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.destino = destino
            Me.fecha_solicitud = fecha_solicitud
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consulta_smsResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consulta_smsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="envio_sms_masivo", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class envio_sms_masivoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public sms As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public destinos As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public fecha_hora As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=7)>  _
        Public campana As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal sms As String, ByVal destinos As String, ByVal fecha_hora As String, ByVal campana As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.sms = sms
            Me.destinos = destinos
            Me.fecha_hora = fecha_hora
            Me.campana = campana
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="envio_sms_masivoResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class envio_sms_masivoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consulta_sms_masivo", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consulta_sms_masivoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public fecha_solicitud As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public campana As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal fecha_solicitud As String, ByVal campana As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.fecha_solicitud = fecha_solicitud
            Me.campana = campana
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consulta_sms_masivoResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consulta_sms_masivoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consultar_saldo", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consultar_saldoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public bolsa As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public nodo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal bolsa As String, ByVal nodo As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.bolsa = bolsa
            Me.nodo = nodo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consultar_saldoResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consultar_saldoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="envio_sms_internacional", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class envio_sms_internacionalRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public destino As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public codigo_pais As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public sms As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal codigo_pais As String, ByVal sms As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.destino = destino
            Me.codigo_pais = codigo_pais
            Me.sms = sms
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="envio_sms_internacionalResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class envio_sms_internacionalResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consulta_sms_internacional", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consulta_sms_internacionalRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public destino As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=5)>  _
        Public codigo_pais As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=6)>  _
        Public fecha_solicitud As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal codigo_pais As String, ByVal fecha_solicitud As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.destino = destino
            Me.codigo_pais = codigo_pais
            Me.fecha_solicitud = fecha_solicitud
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consulta_sms_internacionalResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consulta_sms_internacionalResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="agregar_lista_negra", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class agregar_lista_negraRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public numeros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal numeros As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.numeros = numeros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="agregar_lista_negraResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class agregar_lista_negraResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="eliminar_lista_negra", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class eliminar_lista_negraRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public numeros As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal numeros As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.numeros = numeros
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="eliminar_lista_negraResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class eliminar_lista_negraResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consultar_lista_negra", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consultar_lista_negraRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="consultar_lista_negraResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class consultar_lista_negraResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="pausar_envio_campana", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class pausar_envio_campanaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public instancia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public entidad As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=2)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=3)>  _
        Public nodo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=4)>  _
        Public pausar As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal pausar As String)
            MyBase.New
            Me.instancia = instancia
            Me.entidad = entidad
            Me.usuario = usuario
            Me.nodo = nodo
            Me.pausar = pausar
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="pausar_envio_campanaResponse", WrapperNamespace:="", IsWrapped:=true)>  _
    Partial Public Class pausar_envio_campanaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public RESULTADO As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RESULTADO As String)
            MyBase.New
            Me.RESULTADO = RESULTADO
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface smsexpertPortTypeChannel
        Inherits ServiceReference1.smsexpertPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class smsexpertPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.smsexpertPortType)
        Implements ServiceReference1.smsexpertPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_envio_sms(ByVal request As ServiceReference1.envio_smsRequest) As ServiceReference1.envio_smsResponse Implements ServiceReference1.smsexpertPortType.envio_sms
            Return MyBase.Channel.envio_sms(request)
        End Function
        
        Public Function envio_sms(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal sms As String) As String
            Dim inValue As ServiceReference1.envio_smsRequest = New ServiceReference1.envio_smsRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.sms = sms
            Dim retVal As ServiceReference1.envio_smsResponse = CType(Me,ServiceReference1.smsexpertPortType).envio_sms(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_envio_smsAsync(ByVal request As ServiceReference1.envio_smsRequest) As System.Threading.Tasks.Task(Of ServiceReference1.envio_smsResponse) Implements ServiceReference1.smsexpertPortType.envio_smsAsync
            Return MyBase.Channel.envio_smsAsync(request)
        End Function
        
        Public Function envio_smsAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal sms As String) As System.Threading.Tasks.Task(Of ServiceReference1.envio_smsResponse)
            Dim inValue As ServiceReference1.envio_smsRequest = New ServiceReference1.envio_smsRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.sms = sms
            Return CType(Me,ServiceReference1.smsexpertPortType).envio_smsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consulta_sms(ByVal request As ServiceReference1.consulta_smsRequest) As ServiceReference1.consulta_smsResponse Implements ServiceReference1.smsexpertPortType.consulta_sms
            Return MyBase.Channel.consulta_sms(request)
        End Function
        
        Public Function consulta_sms(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal fecha_solicitud As String) As String
            Dim inValue As ServiceReference1.consulta_smsRequest = New ServiceReference1.consulta_smsRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.fecha_solicitud = fecha_solicitud
            Dim retVal As ServiceReference1.consulta_smsResponse = CType(Me,ServiceReference1.smsexpertPortType).consulta_sms(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consulta_smsAsync(ByVal request As ServiceReference1.consulta_smsRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_smsResponse) Implements ServiceReference1.smsexpertPortType.consulta_smsAsync
            Return MyBase.Channel.consulta_smsAsync(request)
        End Function
        
        Public Function consulta_smsAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal fecha_solicitud As String) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_smsResponse)
            Dim inValue As ServiceReference1.consulta_smsRequest = New ServiceReference1.consulta_smsRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.fecha_solicitud = fecha_solicitud
            Return CType(Me,ServiceReference1.smsexpertPortType).consulta_smsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_envio_sms_masivo(ByVal request As ServiceReference1.envio_sms_masivoRequest) As ServiceReference1.envio_sms_masivoResponse Implements ServiceReference1.smsexpertPortType.envio_sms_masivo
            Return MyBase.Channel.envio_sms_masivo(request)
        End Function
        
        Public Function envio_sms_masivo(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal sms As String, ByVal destinos As String, ByVal fecha_hora As String, ByVal campana As String) As String
            Dim inValue As ServiceReference1.envio_sms_masivoRequest = New ServiceReference1.envio_sms_masivoRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.sms = sms
            inValue.destinos = destinos
            inValue.fecha_hora = fecha_hora
            inValue.campana = campana
            Dim retVal As ServiceReference1.envio_sms_masivoResponse = CType(Me,ServiceReference1.smsexpertPortType).envio_sms_masivo(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_envio_sms_masivoAsync(ByVal request As ServiceReference1.envio_sms_masivoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.envio_sms_masivoResponse) Implements ServiceReference1.smsexpertPortType.envio_sms_masivoAsync
            Return MyBase.Channel.envio_sms_masivoAsync(request)
        End Function
        
        Public Function envio_sms_masivoAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal sms As String, ByVal destinos As String, ByVal fecha_hora As String, ByVal campana As String) As System.Threading.Tasks.Task(Of ServiceReference1.envio_sms_masivoResponse)
            Dim inValue As ServiceReference1.envio_sms_masivoRequest = New ServiceReference1.envio_sms_masivoRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.sms = sms
            inValue.destinos = destinos
            inValue.fecha_hora = fecha_hora
            inValue.campana = campana
            Return CType(Me,ServiceReference1.smsexpertPortType).envio_sms_masivoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consulta_sms_masivo(ByVal request As ServiceReference1.consulta_sms_masivoRequest) As ServiceReference1.consulta_sms_masivoResponse Implements ServiceReference1.smsexpertPortType.consulta_sms_masivo
            Return MyBase.Channel.consulta_sms_masivo(request)
        End Function
        
        Public Function consulta_sms_masivo(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal fecha_solicitud As String, ByVal campana As String) As String
            Dim inValue As ServiceReference1.consulta_sms_masivoRequest = New ServiceReference1.consulta_sms_masivoRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.fecha_solicitud = fecha_solicitud
            inValue.campana = campana
            Dim retVal As ServiceReference1.consulta_sms_masivoResponse = CType(Me,ServiceReference1.smsexpertPortType).consulta_sms_masivo(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consulta_sms_masivoAsync(ByVal request As ServiceReference1.consulta_sms_masivoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_sms_masivoResponse) Implements ServiceReference1.smsexpertPortType.consulta_sms_masivoAsync
            Return MyBase.Channel.consulta_sms_masivoAsync(request)
        End Function
        
        Public Function consulta_sms_masivoAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal fecha_solicitud As String, ByVal campana As String) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_sms_masivoResponse)
            Dim inValue As ServiceReference1.consulta_sms_masivoRequest = New ServiceReference1.consulta_sms_masivoRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.fecha_solicitud = fecha_solicitud
            inValue.campana = campana
            Return CType(Me,ServiceReference1.smsexpertPortType).consulta_sms_masivoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consultar_saldo(ByVal request As ServiceReference1.consultar_saldoRequest) As ServiceReference1.consultar_saldoResponse Implements ServiceReference1.smsexpertPortType.consultar_saldo
            Return MyBase.Channel.consultar_saldo(request)
        End Function
        
        Public Function consultar_saldo(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal bolsa As String, ByVal nodo As String) As String
            Dim inValue As ServiceReference1.consultar_saldoRequest = New ServiceReference1.consultar_saldoRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.bolsa = bolsa
            inValue.nodo = nodo
            Dim retVal As ServiceReference1.consultar_saldoResponse = CType(Me,ServiceReference1.smsexpertPortType).consultar_saldo(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consultar_saldoAsync(ByVal request As ServiceReference1.consultar_saldoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consultar_saldoResponse) Implements ServiceReference1.smsexpertPortType.consultar_saldoAsync
            Return MyBase.Channel.consultar_saldoAsync(request)
        End Function
        
        Public Function consultar_saldoAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal bolsa As String, ByVal nodo As String) As System.Threading.Tasks.Task(Of ServiceReference1.consultar_saldoResponse)
            Dim inValue As ServiceReference1.consultar_saldoRequest = New ServiceReference1.consultar_saldoRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.bolsa = bolsa
            inValue.nodo = nodo
            Return CType(Me,ServiceReference1.smsexpertPortType).consultar_saldoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_envio_sms_internacional(ByVal request As ServiceReference1.envio_sms_internacionalRequest) As ServiceReference1.envio_sms_internacionalResponse Implements ServiceReference1.smsexpertPortType.envio_sms_internacional
            Return MyBase.Channel.envio_sms_internacional(request)
        End Function
        
        Public Function envio_sms_internacional(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal codigo_pais As String, ByVal sms As String) As String
            Dim inValue As ServiceReference1.envio_sms_internacionalRequest = New ServiceReference1.envio_sms_internacionalRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.codigo_pais = codigo_pais
            inValue.sms = sms
            Dim retVal As ServiceReference1.envio_sms_internacionalResponse = CType(Me,ServiceReference1.smsexpertPortType).envio_sms_internacional(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_envio_sms_internacionalAsync(ByVal request As ServiceReference1.envio_sms_internacionalRequest) As System.Threading.Tasks.Task(Of ServiceReference1.envio_sms_internacionalResponse) Implements ServiceReference1.smsexpertPortType.envio_sms_internacionalAsync
            Return MyBase.Channel.envio_sms_internacionalAsync(request)
        End Function
        
        Public Function envio_sms_internacionalAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal codigo_pais As String, ByVal sms As String) As System.Threading.Tasks.Task(Of ServiceReference1.envio_sms_internacionalResponse)
            Dim inValue As ServiceReference1.envio_sms_internacionalRequest = New ServiceReference1.envio_sms_internacionalRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.codigo_pais = codigo_pais
            inValue.sms = sms
            Return CType(Me,ServiceReference1.smsexpertPortType).envio_sms_internacionalAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consulta_sms_internacional(ByVal request As ServiceReference1.consulta_sms_internacionalRequest) As ServiceReference1.consulta_sms_internacionalResponse Implements ServiceReference1.smsexpertPortType.consulta_sms_internacional
            Return MyBase.Channel.consulta_sms_internacional(request)
        End Function
        
        Public Function consulta_sms_internacional(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal codigo_pais As String, ByVal fecha_solicitud As String) As String
            Dim inValue As ServiceReference1.consulta_sms_internacionalRequest = New ServiceReference1.consulta_sms_internacionalRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.codigo_pais = codigo_pais
            inValue.fecha_solicitud = fecha_solicitud
            Dim retVal As ServiceReference1.consulta_sms_internacionalResponse = CType(Me,ServiceReference1.smsexpertPortType).consulta_sms_internacional(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consulta_sms_internacionalAsync(ByVal request As ServiceReference1.consulta_sms_internacionalRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_sms_internacionalResponse) Implements ServiceReference1.smsexpertPortType.consulta_sms_internacionalAsync
            Return MyBase.Channel.consulta_sms_internacionalAsync(request)
        End Function
        
        Public Function consulta_sms_internacionalAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal destino As String, ByVal codigo_pais As String, ByVal fecha_solicitud As String) As System.Threading.Tasks.Task(Of ServiceReference1.consulta_sms_internacionalResponse)
            Dim inValue As ServiceReference1.consulta_sms_internacionalRequest = New ServiceReference1.consulta_sms_internacionalRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.destino = destino
            inValue.codigo_pais = codigo_pais
            inValue.fecha_solicitud = fecha_solicitud
            Return CType(Me,ServiceReference1.smsexpertPortType).consulta_sms_internacionalAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_agregar_lista_negra(ByVal request As ServiceReference1.agregar_lista_negraRequest) As ServiceReference1.agregar_lista_negraResponse Implements ServiceReference1.smsexpertPortType.agregar_lista_negra
            Return MyBase.Channel.agregar_lista_negra(request)
        End Function
        
        Public Function agregar_lista_negra(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal numeros As String) As String
            Dim inValue As ServiceReference1.agregar_lista_negraRequest = New ServiceReference1.agregar_lista_negraRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.numeros = numeros
            Dim retVal As ServiceReference1.agregar_lista_negraResponse = CType(Me,ServiceReference1.smsexpertPortType).agregar_lista_negra(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_agregar_lista_negraAsync(ByVal request As ServiceReference1.agregar_lista_negraRequest) As System.Threading.Tasks.Task(Of ServiceReference1.agregar_lista_negraResponse) Implements ServiceReference1.smsexpertPortType.agregar_lista_negraAsync
            Return MyBase.Channel.agregar_lista_negraAsync(request)
        End Function
        
        Public Function agregar_lista_negraAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal numeros As String) As System.Threading.Tasks.Task(Of ServiceReference1.agregar_lista_negraResponse)
            Dim inValue As ServiceReference1.agregar_lista_negraRequest = New ServiceReference1.agregar_lista_negraRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.numeros = numeros
            Return CType(Me,ServiceReference1.smsexpertPortType).agregar_lista_negraAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_eliminar_lista_negra(ByVal request As ServiceReference1.eliminar_lista_negraRequest) As ServiceReference1.eliminar_lista_negraResponse Implements ServiceReference1.smsexpertPortType.eliminar_lista_negra
            Return MyBase.Channel.eliminar_lista_negra(request)
        End Function
        
        Public Function eliminar_lista_negra(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal numeros As String) As String
            Dim inValue As ServiceReference1.eliminar_lista_negraRequest = New ServiceReference1.eliminar_lista_negraRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.numeros = numeros
            Dim retVal As ServiceReference1.eliminar_lista_negraResponse = CType(Me,ServiceReference1.smsexpertPortType).eliminar_lista_negra(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_eliminar_lista_negraAsync(ByVal request As ServiceReference1.eliminar_lista_negraRequest) As System.Threading.Tasks.Task(Of ServiceReference1.eliminar_lista_negraResponse) Implements ServiceReference1.smsexpertPortType.eliminar_lista_negraAsync
            Return MyBase.Channel.eliminar_lista_negraAsync(request)
        End Function
        
        Public Function eliminar_lista_negraAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal numeros As String) As System.Threading.Tasks.Task(Of ServiceReference1.eliminar_lista_negraResponse)
            Dim inValue As ServiceReference1.eliminar_lista_negraRequest = New ServiceReference1.eliminar_lista_negraRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.numeros = numeros
            Return CType(Me,ServiceReference1.smsexpertPortType).eliminar_lista_negraAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consultar_lista_negra(ByVal request As ServiceReference1.consultar_lista_negraRequest) As ServiceReference1.consultar_lista_negraResponse Implements ServiceReference1.smsexpertPortType.consultar_lista_negra
            Return MyBase.Channel.consultar_lista_negra(request)
        End Function
        
        Public Function consultar_lista_negra(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String) As String
            Dim inValue As ServiceReference1.consultar_lista_negraRequest = New ServiceReference1.consultar_lista_negraRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            Dim retVal As ServiceReference1.consultar_lista_negraResponse = CType(Me,ServiceReference1.smsexpertPortType).consultar_lista_negra(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_consultar_lista_negraAsync(ByVal request As ServiceReference1.consultar_lista_negraRequest) As System.Threading.Tasks.Task(Of ServiceReference1.consultar_lista_negraResponse) Implements ServiceReference1.smsexpertPortType.consultar_lista_negraAsync
            Return MyBase.Channel.consultar_lista_negraAsync(request)
        End Function
        
        Public Function consultar_lista_negraAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String) As System.Threading.Tasks.Task(Of ServiceReference1.consultar_lista_negraResponse)
            Dim inValue As ServiceReference1.consultar_lista_negraRequest = New ServiceReference1.consultar_lista_negraRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            Return CType(Me,ServiceReference1.smsexpertPortType).consultar_lista_negraAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_pausar_envio_campana(ByVal request As ServiceReference1.pausar_envio_campanaRequest) As ServiceReference1.pausar_envio_campanaResponse Implements ServiceReference1.smsexpertPortType.pausar_envio_campana
            Return MyBase.Channel.pausar_envio_campana(request)
        End Function
        
        Public Function pausar_envio_campana(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal pausar As String) As String
            Dim inValue As ServiceReference1.pausar_envio_campanaRequest = New ServiceReference1.pausar_envio_campanaRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.pausar = pausar
            Dim retVal As ServiceReference1.pausar_envio_campanaResponse = CType(Me,ServiceReference1.smsexpertPortType).pausar_envio_campana(inValue)
            Return retVal.RESULTADO
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_smsexpertPortType_pausar_envio_campanaAsync(ByVal request As ServiceReference1.pausar_envio_campanaRequest) As System.Threading.Tasks.Task(Of ServiceReference1.pausar_envio_campanaResponse) Implements ServiceReference1.smsexpertPortType.pausar_envio_campanaAsync
            Return MyBase.Channel.pausar_envio_campanaAsync(request)
        End Function
        
        Public Function pausar_envio_campanaAsync(ByVal instancia As String, ByVal entidad As String, ByVal usuario As String, ByVal nodo As String, ByVal pausar As String) As System.Threading.Tasks.Task(Of ServiceReference1.pausar_envio_campanaResponse)
            Dim inValue As ServiceReference1.pausar_envio_campanaRequest = New ServiceReference1.pausar_envio_campanaRequest()
            inValue.instancia = instancia
            inValue.entidad = entidad
            inValue.usuario = usuario
            inValue.nodo = nodo
            inValue.pausar = pausar
            Return CType(Me,ServiceReference1.smsexpertPortType).pausar_envio_campanaAsync(inValue)
        End Function
    End Class
End Namespace
