Imports System.IO
Imports System.Net
Imports System.Net.Http
Imports System.Web.Http

Namespace Controllers
    Public Class SAPALController
        Inherits ApiController

        <HttpGet>
        <Route("api/SAPAL/busqueda")>
        Public Function busqueda()
            Return "metodo1"
        End Function

        <HttpGet>
        <Route("api/SAPAL/pdf")>
        Public Function pdf()
            Dim Pagina As String = ""

            Pagina = generaHTML()

            Dim response = New HttpResponseMessage()
            response.Content = New StringContent(Pagina)
            response.Content.Headers.ContentType = New Headers.MediaTypeHeaderValue("text/html")

            Return response
        End Function
        Public Function generaHTML()
            Dim Pagina As String = ""

            Pagina += "<html Class=''><head>"
            Pagina += "<link type ='text/css' rel='stylesheet' charset='UTF-8' href='https://translate.googleapis.com/translate_static/css/translateelement.css'></head>"
            Pagina += "<body style='"
            Pagina += "background: white;"
            Pagina += "position: absolute;"
            Pagina += "height: auto;"
            Pagina += "font-family: arial black;"
            Pagina += "width: 100%;"
            Pagina += "padding-bottom: 5px;"
            Pagina += "padding:0px;'>"
            Pagina += "<div style='"
            Pagina += "width: calc(13.5 * 37.79527559px);"
            Pagina += "height: calc(23.4 * 37.79527559px);"
            Pagina += "background: white;"
            Pagina += "position: relative;"
            Pagina += "border: 3px dashed black;"
            Pagina += "margin-bottom: 10px;"
            Pagina += "float: left;"
            Pagina += "margin-left: calc(50% - (6.25*37.79527559px));"
            Pagina += "min-height: calc(23.4 * 37.79527559px);"
            Pagina += "max-height: calc(23.4 * 37.79527559px);'>"
            Pagina += "<table style='width:100%;position:relative;height:100%;'>"
            Pagina += "<thead>"
            Pagina += "<tr>"
            Pagina += "<th colspan='2' style=' width: 30%;'>"
            Pagina += "<img style='width: 180px;position: relative;top: 0px;left: 0px;z-index: 0;position: absolute;/* margin-top: 15px; */' src='https://res.cloudinary.com/apd/image/upload/v1593444335/apd_digital/logo_p6nto0_amibzm.jpg'></th>"
            Pagina += "<th colspan='2' style='"
            Pagina += "padding: inherit;"
            Pagina += "width: 50%;"
            Pagina += "z-index: 1;'>"
            Pagina += "<p style='margin:0px;text-align: center;padding: 0px;position: relative;margin-top: 15px;z-index: 33;'><span style='font-size: 12;'>SISTEMA DE AGUA POTABLE Y ALCANTARILLADO <br>DEL MUNICIPIO DE LERDO, DGO.</span><br>"
            Pagina += "<span style='font-size: 8px;'>C.CUAUHTEMOC No. 409 COL. CENTRO CD. LERDO, DGO. C.P. 35150 R.F.C SAP-990715-876</span></p>"
            Pagina += "<table style='"
            Pagina += "width: 100%;"
            Pagina += "margin-top: 15px;"
            Pagina += "margin-right: 10px;"
            Pagina += "padding-right: 15px;'>"
            Pagina += "<thead>"
            Pagina += "<tr>"
            Pagina += "<tr>"
            Pagina += "<tr>"
            Pagina += "<td style='width: 24%;'>"
            Pagina += "</td>"
            Pagina += "<td style='width: 38%;/* margin-right: 2%; */'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 12px;width:100%;text-align: center;border: 1px solid black;font-size: 8px;border-radius: 10px 10px 0px 0px;'>RECIBO No.</div>"
            Pagina += "<div style='height: 40px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>*&amp;*CODE1*&amp;*</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float: left;border: 1px solid black;font-size: 8px;height: 12px;text-align: center;width:100%;'>FECHA DE REMISIÓN</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:100%;border: 1px solid black;border-radius: 0 0 10px 10px;'>*&amp;*CODE3*&amp;*</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "<td style='width: 38%;/* margin-right: 10px; */'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 12px;width:100%;text-align: center;border: 1px solid black;font-size: 7px;border-radius: 10px 10px 0px 0px;'>CUENTA</div>"
            Pagina += "<div style='height: 40px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>*&amp;*CODE2*&amp;*</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float: left;border: 1px solid black;font-size: 7px;height: 12px;text-align: center;width:100%;'>FECHA DE VENCIMIENTO</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:100%;border: 1px solid black;border-radius: 0 0 10px 10px;'>*&amp;*CODE4*&amp;*</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "</th>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "<tbody>"
            Pagina += "</tbody>"
            Pagina += "</table>"
            Pagina += "<table style=' width:calc(100% - 30px);"
            Pagina += "margin-left: 15px;"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead style='width:100%;'>"
            Pagina += "<tr>"
            Pagina += "<td style='width:40%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='position:relative;float:left;height: 50px;width:100%;padding-left: 5px;FONT-SIZE: 4px;text-align: center;font-size: 7px;'>"
            Pagina += "<img src='https://res.cloudinary.com/apd/image/upload/v1593706552/sapal/descarga_xaiada.jpg' style='"
            Pagina += "HEIGHT: 40px;"
            Pagina += "position:relative;"
            Pagina += "float:left;"
            Pagina += "width: 30%;"
            Pagina += "MARGIN-LEFT: 35%;"
            Pagina += "MARGIN-RIGHT: 35%;'>"
            Pagina += "<div style='position:relative;float:left'>05000</div>"
            Pagina += "<div style='position:relative;float:left'>*&amp;*CODE27*&amp;*</div>"
            Pagina += "<div style='position:relative;float:left'>55555555555555555555</div>"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "<td style='width: 60%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%;padding-left: 10px;'>"
            Pagina += "*&amp;*CODE24*&amp;*"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<table style='"
            Pagina += "width:calc(100% - 30px);"
            Pagina += "margin-left: 15px;"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead>"
            Pagina += "<tr>"
            Pagina += "<td style='width: 33%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;width:100%;text-align: center;border: 1px solid black;font-size: 9px;border-radius: 10px 10px 0px 0px;'>INFORMACION DE CONSUMO</div>"
            Pagina += "<div style='height: 120px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>*&amp;*CODE5*&amp;*</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float: left;border: 1px solid black;font-size: 10px;height: 18px;padding-top: 4px;text-align: center;width:100%;'>NUMERO DE MEDIDOR</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:100%;border: 1px solid black;border-radius: 0 0 10px 10px;'>*&amp;*CODE6*&amp;*</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "<td style='width: 66%;' colspan='2'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;width:100%;text-align: center;border: 1px solid black;font-size: 10px;border-radius: 10px 10px 0px 0px;'>"
            Pagina += "<div style='width:70%;position:relative;float:left;text-align:left'>CONSUMO FACTURADO</div>"
            Pagina += "<div style='width:30%;position:relative;float:left;text-align:left'>IMPORTE</div>"
            Pagina += "</div>"
            Pagina += "<div style='height: 120px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>"
            Pagina += "*&amp;*CODE10*&amp;*"
            Pagina += "</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float: left;border: 1px solid black;font-size: 7px;height: 22px;text-align: center;width:100%;'>"
            Pagina += "<div style='width:50%;position:relative;float:left;text-align:left'>"
            Pagina += "<div style='width:50%;position:relative;float:left;text-align:center'>ADEUDO DE <br>CONVENIO</div>"
            Pagina += "<div style='width:50%;position:relative;float:left;text-align:center'>PERIODOS <br>ADEUDO</div>"
            Pagina += "</div>"
            Pagina += "<div style='width:50%;position:relative;float:left;text-align:center;font-size:10px;margin-top: 4px;'>ULTIMO PAGO</div>"
            Pagina += "</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:100%;text-align: center;FONT-SIZE: 10px;border: 1px solid black;border-radius: 0 0 10px 10px;'>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:25%;'>"
            Pagina += "*&amp;*CODE7*&amp;*"
            Pagina += "</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:25%;'>"
            Pagina += "*&amp;*CODE8*&amp;*"
            Pagina += "</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:50%;'>"
            Pagina += "*&amp;*CODE9*&amp;*"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<table style='"
            Pagina += "width:calc(100% - 30px);"
            Pagina += "margin-left: 15px;"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead>"
            Pagina += "<tr><td style='width:100%;font-weight: bold;font-size: 12px;background:black;color:white;text-align:center;font-family: arial black;'>CONSUMOS ANTERIORES Y DATOS GENERALES</td></tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<table style='"
            Pagina += "margin-left: 15px;"
            Pagina += "width:calc(100% - 30px);"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead>"
            Pagina += "<tr>"
            Pagina += "<td style='width:66%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;width:100%;text-align: center;border: 1px solid black;font-size: 10px;border-radius: 10px 10px 0px 0px;'>ESTADISTICAS DE CONSUMO</div>"
            Pagina += "<div style='height: 65px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>*&amp;*CODE14*&amp;*</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;width:100%;font-size: 8px;text-align: center;border: 1px solid black;border-radius: 0 0 10px 10px;'>"
            Pagina += "<div style='position:relative;width:25%;float:left;height:100%'>"
            Pagina += "PAGO PUNTUAL</div>"
            Pagina += "<div style='position:relative;width:25%;float:left;height:100%'>"
            Pagina += "<img src='https://res.cloudinary.com/apd/image/upload/v1593706552/sapal/descarga_xaiada.jpg' style='"
            Pagina += "HEIGHT: 30px;'></div>"
            Pagina += "<div style='position:relative;width:25%;float:left;height:100%'>"
            Pagina += "<img src='https://res.cloudinary.com/apd/image/upload/v1593706719/sapal/super_mweykn.jpg' style='"
            Pagina += "height: 30px;'></div>"
            Pagina += "<div style='position:relative;width:25%;float:left;height:100%'>"
            Pagina += "<img src='https://res.cloudinary.com/apd/image/upload/v1593706719/sapal/sumerka_esoqxw.png' style='"
            Pagina += "height: 30px;'></div>"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "<td style='width: 33%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%;TEXT-ALIGN: CENTER;'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;width:100%;text-align: center;border: 1px solid black;font-size: 10px;border-radius: 10px 10px 0px 0px;'>SERVICIO</div>"
            Pagina += "<div style='height: 20px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>"
            Pagina += "*&amp;*CODE11*&amp;*"
            Pagina += "</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;width:100%;text-align: center;border: 1px solid black;font-size: 10px;'>GIRO</div>"
            Pagina += "<div style='height: 20px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>*&amp;*CODE12*&amp;*</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float: left;border: 1px solid black;font-size: 10px;height: 15px;text-align: center;width:100%;'>NIVEL</div>"
            Pagina += "<div style='height: 20px;position:relative;float:left;width:100%;border: 1px solid black;border-radius: 0 0 10px 10px;'>*&amp;*CODE13*&amp;*</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<table style=' width:calc(100% - 30px);"
            Pagina += "margin-left: 15px;"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead style='width:100%;'>"
            Pagina += "<tr>"
            Pagina += "<td style='width:66%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 50px;width:100%;padding-left: 5px;text-align: left;border: 1px solid black;font-size: 10px;border-radius: 10px 10px 10px 10px;'>"
            Pagina += "*&amp;*code25*&amp;*<br><br>PAGA A TIEMPO Y NO PIERDAS TU CONVENIO"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "<td style='width: 33%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%;padding-left: 10px;'>"
            Pagina += "*&amp;*CODE24*&amp;*"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<hr style='"
            Pagina += "border-top: 2px dashed  #ff0505;"
            Pagina += "margin-bottom: 0px;"
            Pagina += "color: red;"
            Pagina += "'>"
            Pagina += "<table style ='"
            Pagina += "width : calc(100% - 30px);"
            Pagina += "margin-left: 15px;"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead>"
            Pagina += "<tr><td style='width:100%;font-weight: bold;font-size: 12px;background:black;color:white;text-align:center;font-family: arial black;'>TALON DE PAGO</td></tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<table style='"
            Pagina += "margin-left: 15px;"
            Pagina += "margin-right: 15px;'>"
            Pagina += "<thead>"
            Pagina += "<tr>"
            Pagina += "<td colspan='2' style='width:40%;'>"
            Pagina += "<div style='position:relative;float:left;width:100%'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;width:100%;text-align: center;border: 1px solid black;font-size: 10px;border-radius: 10px 10px 0px 0px;'>INFORMACION DE CONSUMOS</div>"
            Pagina += "<div style='height: 80px;position:relative;float:left;width:100%;border-right: 1px solid black;border-left: 1px solid black;'>*&amp;*CODE16*&amp;*</div>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float: left;border: 1px solid black;font-size: 10px;height: 15px;text-align: center;width:100%;'>"
            Pagina += "<div style='width:50%;position:relative;float:left'>CUENTA</div>"
            Pagina += "<div style='width:50%;position:relative;float:left'>RECIBO NO.</div>"
            Pagina += "</div>"
            Pagina += "<div style='height: 30px;position:relative;float:left;font-size: 11px;width:100%;border: 1px solid black;border-radius: 0 0 10px 10px;'>"
            Pagina += "<div style='width:50%;position:relative;float:left;margin-top: 7px;'>*&amp;*CODE18*&amp;*</div>"
            Pagina += "<div style='width:50%;position:relative;float:left;margin-top: 7px;'>*&amp;*CODE19*&amp;*</div>"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "<td style='width: 70%;'>"
            Pagina += "<div style='position:relative;float:left;border: 1px solid black;width:100%;border-radius: 10px 10px 10px 10px;'>"
            Pagina += "<div style='background: #d8d8d8;position:relative;float:left;height: 15px;border-bottom: 1px solid black;width:100%;text-align: center;/* border: 1px solid black; */font-size: 10px;border-radius: 10px 10px 0px 0px;'>"
            Pagina += "<div style='width:50%;position:relative;float:left;'>CONSUMO FACTURADO</div>"
            Pagina += "<div style='width:50%;position:relative;float:left;'>IMPORTE</div>"
            Pagina += "</div>"
            Pagina += "<div style='height: 80px;position:relative;float:left;width:100%;/* border-right: 1px solid black; *//* border-left: 1px solid black; */'>"
            Pagina += "*&amp;*CODE17*&amp;*</div>"
            Pagina += "<div style='position:relative;float: left;/* border: 1px solid black; */font-size: 10px;border-top: 1px solid black;height: 45px;text-align: center;border-radius: 0 0 0px 10px;width: 50%;'>"
            Pagina += "<div style='width:100%;background: #d8d8d8;height: 22px;border-bottom: 1px solid black;/* border: 1px solid black; */position:relative;'>"
            Pagina += "<div style='width:50%;position:relative;float:left;font-size: 8px;'>"
            Pagina += "ADEUDO DE <br>CONVENIO"
            Pagina += "</div>"
            Pagina += "<div style='width:50%;position:relative;float:left;font-size: 8px;'>"
            Pagina += "PERIODOS<br> ADEUDO"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "<div style='width:100%;height: 30px;position:relative;float:left;font-size: 8px;'>"
            Pagina += "<div style='width:50%;position:relative;float:left;margin-top: 7px;'>*&amp;*CODE20*&amp;*</div>"
            Pagina += "<div style='width:50%;position:relative;float:left;margin-top: 7px;'>*&amp;*CODE21*&amp;*</div>"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "<div style='position:relative;float: left;/* border: 1px solid black; */font-size: 10px;border-top: 1px solid black;height: 45px;border-left: 1px solid black;text-align: center;border-radius: 0 0 10px 0px;width: calc(50% - 3px);'>"
            Pagina += "*&amp;*CODE22*&amp;*"
            Pagina += "</div>"
            Pagina += "</div>"
            Pagina += "</td>"
            Pagina += "</tr>"
            Pagina += "</thead>"
            Pagina += "</table>"
            Pagina += "<div class='goog-te-spinner-pos'><div class='goog-te-spinner-animation'><svg xmlns='http://www.w3.org/2000/svg' class='goog-te-spinner' width='96px' height='96px' viewBox='0 0 66 66'><circle class='goog-te-spinner-path' fill='none' stroke-width='6' stroke-linecap='round' cx='33' cy='33' r='30'></circle></svg></div></div></body></html>"

            Return Pagina
        End Function
    End Class
End Namespace